name: akatsuki_attendance_system
description: Akatsuki Attendance System Flutter Project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:
  fonts:
    - family: GlossAndBloom
      fonts:
        - asset: assets/fonts/Gloss_And_Bloom.ttf

  uses-material-design: true

